openapi: 3.0.0
info:
  title: "API of mysterious berries and machines"
  description: "An API allowing to obtain information on machines and the berries's pokemon."
  version: "1.0"

servers:
  - url: "http://localhost:3000/"
  - url: 'https://joan-jomaora.herokuapp.com/ ?????? TODO'    #TODO

components:
  schemas:
    Machine:
      type: object
      properties:
        id:
          type: integer
        item:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        move:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        version_group:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string

    Berrie:
      type: object
      properties:
        firmness:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        flavors: 
          type: array
          items:
            type: object
            properties:
              flavor:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    url:
                      type: string
              potency:
                type: integer
        growth_time:
          type: integer
        id:
          type: integer
        item:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        max_harvest:
          type: integer
        name:
          type: string
        natural_gift_power:
          type: integer
        natural_gift_type:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        size:
          type: integer
        smoothness:
          type: integer
        soil_dryness:
          type: integer

paths:
  /machine:
    get:
      tags:
        - "machine"
      summary: "Informations for specific machine"
      parameters:
        - in: query
          name: machine
          description: Machine name or ID.
          schema:
            type: string
          example: 1
      responses:
        "200":
          description: Result found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Machine"
              properties:
                name:
                  type: string
            text/plain:
              schema:
                $ref: "#/components/schemas/Machine"
              properties:
                name:
                  type: string
        "400":
          description: Machine name or ID is missing.
        "404":
          description: This machine doesn't exist.

  /berry:
    get:
      tags:
        - "berry"
      summary: "Informations for specific berry."
      parameters:
        - in: query
          name: berry
          description: Berry name or ID.
          schema:
            type: string
          example: cheri
      responses:
        "200":
          description: Result found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Berrie"
        "400":
          description: Berry name or ID is missing.
        "404":
          description: This berry doesn't exist.
